// This file is generated by `studio sync`
declare module 'astro:db' {
	export const db: import("@astrojs/db/runtime").SqliteDB;
	export const dbUrl: string;

	export const ViewCount: import("@astrojs/db/runtime").Table<
		"ViewCount",
		{"slug":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"slug","collection":"ViewCount","primaryKey":true}},"count":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"count","collection":"ViewCount","primaryKey":false,"optional":false}},"lastViewed":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"lastViewed","collection":"ViewCount"}}}
	>;
}
